//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Currencies = newCurrenciesTable("public", "currencies", "")

type currenciesTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnInteger
	Code      postgres.ColumnString
	Dimension postgres.ColumnInteger
	MinValue  postgres.ColumnInteger
	MaxValue  postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type CurrenciesTable struct {
	currenciesTable

	EXCLUDED currenciesTable
}

// AS creates new CurrenciesTable with assigned alias
func (a CurrenciesTable) AS(alias string) *CurrenciesTable {
	return newCurrenciesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CurrenciesTable with assigned schema name
func (a CurrenciesTable) FromSchema(schemaName string) *CurrenciesTable {
	return newCurrenciesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CurrenciesTable with assigned table prefix
func (a CurrenciesTable) WithPrefix(prefix string) *CurrenciesTable {
	return newCurrenciesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CurrenciesTable with assigned table suffix
func (a CurrenciesTable) WithSuffix(suffix string) *CurrenciesTable {
	return newCurrenciesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCurrenciesTable(schemaName, tableName, alias string) *CurrenciesTable {
	return &CurrenciesTable{
		currenciesTable: newCurrenciesTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newCurrenciesTableImpl("", "excluded", ""),
	}
}

func newCurrenciesTableImpl(schemaName, tableName, alias string) currenciesTable {
	var (
		IDColumn        = postgres.IntegerColumn("id")
		CodeColumn      = postgres.StringColumn("code")
		DimensionColumn = postgres.IntegerColumn("dimension")
		MinValueColumn  = postgres.IntegerColumn("min_value")
		MaxValueColumn  = postgres.IntegerColumn("max_value")
		allColumns      = postgres.ColumnList{IDColumn, CodeColumn, DimensionColumn, MinValueColumn, MaxValueColumn}
		mutableColumns  = postgres.ColumnList{CodeColumn, DimensionColumn, MinValueColumn, MaxValueColumn}
	)

	return currenciesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		Code:      CodeColumn,
		Dimension: DimensionColumn,
		MinValue:  MinValueColumn,
		MaxValue:  MaxValueColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
