//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Balances struct {
	ID         int64 `sql:"primary_key"`
	CustomerID int64
	Sum        int64
	CurrencyID int32
}
